### ISSUE TITLE
Generic scraper, query planner

### ISSUE THREAD

**Issue by afmika** [futureg-lab/mx-scraper#100]
# Description
Implement a generic scraper to allow users to write basic scripts
```bash
mx-scraper --from-plan query_plan.yaml arg1=val1 arg2=val2 ...
```
A plan can also be used inside a plugin, the cli parameters can be specified programmatically.
```typescript
// some plugin's getBook
const plan = QueryPlan.load("plan.yaml").withParams({
  arg1: "val1",
  arg2: "val2"
});
const book = plan.run((url, index, total, err) => {
  console.log("Parsing", url, index, "/", total, err ? "[Fail]": "[Ok]");
});
assert(book != null);
return book;
```

# Implementation
The idea is to define a fetch `plan` inside a yaml file

### Case 1: retrieving pictures on a page
```yaml
version: 1.0.0
target: https://some.link/to/pics
title: Pokemon
filter: 
  select: "img"
  where: "attr.src: %.%  & attr.alt: %Pikachu%"
```

### Case 2: Retrieving pictures on multiple links with the same filter
```yaml
version: 1.0.0
target: [ "http://link.one", "http://link.two", "http://link.three" ]
filter: 
  select: "img"
  where: "attr.src: %.jpg"
```

### Case 3: Plan a generic scraper
```yaml
version: 1.0.0
target: https://some.link?foo={cli_param}&album={counter1}&page={counter2}
title: Some title for the batch (can be inferred from the page)

# applied to each generated target
filter: 
  select: "a"
  where: "attr.class: %pic"
  followLink: # works for <a/> only
    filter: "img"
    where: "attr.src: %.jpg"

iterate:
  counter1:
    range: [1, 10]
    onError: break
    each: 
      counter2: 
       range: [1, 5]
       onError: continue
```
